shortener/urls.py
from django.urls import path

from . import views

app_name = 'shortener'
urlpatterns = [
    path('', views.home, name='home'),
    path('save/', views.save, name='save'),
    path('<url_id>/', views.deflect, name = 'deflect'),
]

urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),
]

shortener/models.py
from django.db import models

class Redirect(models.Model):
    url = models.CharField(max_length = 300)
    shortHand = models.CharField(max_length = 15)

shortener/views.py
import string
import random

from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages

from .models import Redirect

# Create your views here.
def home(request):
    return render(request, 'shortener/home.html')

def save(request):
    url = request.POST['url']
    shortcut = request.POST['shortcut']
    if shortcut == '':
        while Redirect.objects.filter(shortHand = shortcut) or shortcut =='': # generate random key and check that it isn't already being used. 
            shortcut = ''.join(random.choices(string.ascii_uppercase + string.digits, k=7))
    if Redirect.objects.filter(shortHand = shortcut): # if shortcut already exists in database
        messages.error(request, 'That new url name is already being used. Please choose another new url name.')
    elif url == '':
        messages.error(request, 'Please make sure that you have input a url to be redirected to.')
    else:
        entry = Redirect(url = url, shortHand = shortcut)
        entry.save()
        messages.success(request, f'Success! You can now navigate to {entry.url} by typing localhost:8000/{entry.shortHand} into your search bar.')

    return HttpResponseRedirect(request.META["HTTP_REFERER"])

def deflect(request, url_id):
    entry = get_object_or_404(Redirect, shortHand = url_id)
    return redirect(entry.url)

shortener/templates/shortener/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<title> URL Shortener </title>
		<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="{% static 'shortener/style.css' %}">
	</head>
    <body>
        <div class="white">
		<h1>URL Shortener</h1>
        <form action="{% url 'shortener:save' %}" method = 'post'>
            {% csrf_token %}
            <label for="url"> Type the full url of the website you want to be redirected to. </label>
            <br>
            <input id="url" name="url">
            <br>
            <label for="shortcut">Input what you would like the new url to be. If you don't care, leave this box blank. </label>
            <br>
            <input id="shortcut" name="shortcut">
            <br>
            <button id = "submit">Submit</button>
        </form>
        
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        <div>
        {% endif %}
        </div>
	</body>
</html>